### ISSUE TITLE
Setting the BigchainDB nodes attribute propagates wherever relevant 

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#107]
Changing, (whether it is via a setter, or directly) the `nodes` attribute on a BigchainDB instance will cause the `transport` attribute to be out of sync with the change. Briefly, the change need to be applied to:

`BigchainDB --> transport --> pool of connections`
### Notes
- This issue is more concerned about consistency
- One way could be to remove the `_nodes` attribute

**Comment by sohkai** [comment]
Some thoughts:

- Don't really see the point, at least at the moment, for a driver to be able to change nodes. Why not just make another driver instance to this other node? We don't hold any important state in the driver right now.
- If we want to avoid being able to set the `nodes` attribute, assuming we don't like the `_nodes` shim, we can start looking at immutability.
