### ISSUE TITLE
Implement BigchainDB.unspents.get

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#108]
Initial prerequisite: https://github.com/bigchaindb/bigchaindb/pull/624 (taken care of in https://github.com/bigchaindb/bigchaindb/pull/955)

**Comment by StatelessToken** [comment]
https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-usage.html?highlight=escrow#crypto-conditions-advanced

The Docs still lead back here via a Todo box.
