### ISSUE TITLE
Support "granular" transaction creation steps

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#109]
Creating a transaction via `BigchainDB.transactions.create` involves three main steps:
1. Creation of the dictionary representing the transaction for the given user, and data payload.
2. Signature of the transaction, resulting in a new dictionary
3. Broadcast the transaction to one or more BigchainDB server nodes.

The above three steps are not directly available via the bigchaindb driver, and it is the goal of this ticket to make them available.

**Comment by StatelessToken** [comment]
https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-usage.html?highlight=escrow#crypto-conditions-advanced

The docs still lead here via a Todo box.
