### ISSUE TITLE
Decide how to record changes in new versions, and do that

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#137]
Should we maintain the `HISTORY.rst` file (created by cookiecutter) or just delete it and everything that uses it? See the discussion in the closed PR #135 

Should we [keep a Change Log](http://keepachangelog.com/en/0.3.0/) (akin to BigchainDB Server)?

Should we do both?

Should we do something _else_ to record changes in new versions?

**Comment by vrde** [comment]
Personally, I don't care if it's `.md` or `.rst` (even if `.md` pleases my :eyes: more).

> Should we keep a Change Log (akin to BigchainDB Server)?

:+1: for it. It's simple and we already use it.

**Comment by sbellem** [comment]
As @ttmc pointed out the `HISTORY.rst` file was created by the `cookiecutter` tool.  I do not mind to rename it to `CHANGELOG,rst`. 

I prefer to keep the `rst` format because it can be integrated more easily elsewhere, such as Sphinx docs, or PyPI.

**Comment by sohkai** [comment]
Closing with #161.
