### ISSUE TITLE
Throw a RuntimeError if not Python 3.5+

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#139]
This would have to be added in `setup.py`, e.g.:

```python
import sys

if sys.version_info < (3, 5):
    raise RuntimeError('Python 3.5+ required.')
```

**Comment by vrde** [comment]
Question, can we enforce this in the `classifiers` key in `setup.py`?

**Comment by sbellem** [comment]
> Question, can we enforce this in the classifiers key in setup.py?

I doubt. The classifier is already set as it should be. See https://github.com/bigchaindb/bigchaindb-driver/blob/master/setup.py#L65-L66
