### ISSUE TITLE
Support python 3.4

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb-driver#145]
BigchainDB supports python 3.4, so it's odd that the driver wouldn't. I don't think there's anything in the code that doesn't let us do this, so adding tox tests for 3.4 might be enough.

Also requires a docs change.

**Comment by sbellem** [comment]
It was intentional to support `>= 3.5`.

**Comment by sbellem** [comment]
> it's odd that the driver wouldn't

Why so? A driver could even be in a different language. There is no need for alignment for any sort here.
