### ISSUE TITLE
Document current architecture design and vision/roadmap

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#156]
Until there's a good description for this issue see https://github.com/bigchaindb/bigchaindb-driver/issues/156#issuecomment-321561704 for an explanation of why this issue exists.

**Comment by kremalicious** [comment]
sounds like a vague, almost unachievable task not really suited to be done within the python driver context?

**Comment by sbellem** [comment]
> sounds like a vague, almost unachievable task not really suited to be done within the python driver context?

Well, I wish to keep this opened as this is important because the current implementation is partial with respect to what the architecture allows, and was planned to be.

**Comment by TimDaub** [comment]
Agreed with @sbellem above.
Also with the upcoming architectural changes, security assumptions for BigchainDB drivers might change. Ultimately, we want security assumptions to be documented for the drivers. Let's leave it open and take care about it after the architectural changes have stabilized.

**Comment by sbellem** [comment]
In any case, it is a good thing that the existence of this issue did get questioned as it had been left behind.

Will try to add more information as time goes.
