### ISSUE TITLE
Be consistent with the usage of command line prompts

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#159]
This applies to the bash-like prompts, represented with a dollar sign `$`, and the python primary and secondary prompts represented, by `>>>` and `...` respectively.

Although an argument can be made about the impracticality of the presence of prompt symbols when copying and pasting examples, the prompt symbols do help to distinguish between the command and its output. The latter advantage has been judged important enough to chose to use prompt.

**Comment by sbellem** [comment]
closing as this has been resolved for the most part at least -- OK @sohkai ?

**Comment by sohkai** [comment]
Sounds good.
