### ISSUE TITLE
Add bigchaindb master in travis

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#165]
Add a matrix row to travis that will run the client tests against BigchainDB server master branch. 

Since this may fail, the following docs can be followed to tolerate failures: https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail

**Comment by kremalicious** [comment]
Travis runs `master` right now so this should be closed?

**Comment by sbellem** [comment]
> Travis runs master right now so this should be closed?

I just refined the description to clarify. The current tests are running against the latest release of BigchainDB (server), not the `master` branch.

See https://github.com/bigchaindb/bigchaindb-driver/blob/master/.ci/travis-install.sh#L10

So in addition to installing the server with `pip install bigchaindb`, a new row in travis would have bigchaindb installed via:

```
pip install git+https://github.com/bigchaindb/bigchaindb-driver.git
```
