### ISSUE TITLE
Review name of main class: "BigchainDB": implict or explicit "DB"

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#18]
The question is:

"Should we make the "DB" implicit, or explicit?"

```python
class Bigchain:
    """Main class to establish a connection to one or more BigchainDB nodes."""
```

OR

```python
class BigchainDB:
    """Main class to establish a connection to one or more BigchainDB nodes."""
```

**Comment by ttmc** [comment]
The word "Bigchain" is a legacy word from the days when it was the name of the overall project. Yes, "BigchainDB" has many syllables, but it's the name of the project.

**Comment by sohkai** [comment]
@ttmc But you almost never work with a `*DB` class when using a driver. You import RethinkDB as `rethink` (or just `r`); you import MongoDB as `mongo` in most instances. This pattern is pretty standard.

**Comment by sohkai** [comment]
cc @diminator @vrde @TimDaub, would be nice to have some votes on this. (Just thumbs up or down on the issue is fine).

**Comment by TimDaub** [comment]
> The word "Bigchain" is a legacy word from the days when it was the name of the overall project. Yes, "BigchainDB" has many syllables, but it's the name of the project.

I second that.

**Comment by ttmc** [comment]
From the MongoDB docs:

"PyMongo is the recommended way to work with MongoDB from Python."

```python
import pymongo
```

**Comment by sbellem** [comment]
@vrde @diminator @sohkai how about we close this issue?

**Comment by sohkai** [comment]
Sure, I don't think we came to any consensus on this.
