### ISSUE TITLE
How to look up a transaction while using a particular key

### ISSUE THREAD

**Issue by Flaise** [bigchaindb/bigchaindb-driver#200]
The way to look up a past transaction appears to be something like this:

    transaction = BigchainDB().transactions.retrieve(transaction_id)

It appears, though, to use whichever keys I last used to write a transaction. Is there a way to specify which public or private key to use to look up the transaction?

**Comment by sbellem** [comment]
Hi, 
 
 we have yet to provide the API endpoint on the server side (https://github.com/bigchaindb/bigchaindb/pull/830). This should be done very soon.

**Comment by sbellem** [comment]
@Flaise we have just added the HTTP API endpoint to get unspent conditions, both on server and driver sides. Please note that the new endpoint is only available on **master** branches, and should be part of the 0.9 and 0.2 releases for the server and driver respectively. You are welcome to try out the master branches, and we'll be happy to answer your questions if you have any.

The driver documentation of the endpoint is [here](https://docs.bigchaindb.com/projects/py-driver/en/master/libref.html#bigchaindb_driver.driver.UnspentsEndpoint.get)

We have yet to write some examples. In the meantime, the above linked documentation contains a small example I will reproduce here for convenience:

> Given a transaction with _id_ `da1b64a907ba54` having an _ed25519_ condition (at index `0`) with `alice`’s public key:
>
> ```python
> >>> bdb = BigchainDB()
> >>> bdb.unspents.get(alice_pubkey)
> ... ['../transactions/da1b64a907ba54/conditions/0']
> ```

The server docs for `GET /unspents` are [here](https://docs.bigchaindb.com/projects/server/en/master/drivers-clients/http-client-server-api.html#get-unspents)

Let us know if you need help!

**Comment by sohkai** [comment]
#231 has updated the `/unspent` functionality to `/outputs` (accessible via `.outputs.get()`).
