### ISSUE TITLE
Problem with while loop in Basic Usage Examples when done by script

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#209]
This problem was reported by Thomas from Microsoft. I reproduced it on my machine.

* bigchaindb version: 0.8.0
* bigchaindb-driver version: 0.1.3
* Python version: 3.5.2
* Operating System: Ubuntu 14.04

### Setup

1. Install the versions as above.
2. Run RethinkDB and BigchainDB locally.
3. Run the following Python script (based on the Python Driver Basic Usage Examples):
```python
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair

bdb = BigchainDB('http://localhost:9984/api/v1')

alice, bob = generate_keypair(), generate_keypair()
bicycle = {'data': {'bicycle': {'serial_number': 'abcd1234','manufacturer': 'bkfab'}}}
metadata = {'planet': 'earth'}

prepared_creation_tx = bdb.transactions.prepare(operation='CREATE', owners_before=alice.verifying_key, asset=bicycle, metadata=metadata)

fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx, private_keys=alice.signing_key)

print(fulfilled_creation_tx)

sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)

txid = fulfilled_creation_tx['id']

print(txid)

print(sent_creation_tx == fulfilled_creation_tx)

trials = 0
while bdb.transactions.status(txid).get('status') != 'valid' and trials < 100:
    trials += 1

print(trials)
print(bdb.transactions.status(txid))
```

### What Happened

Here's my terminal output:
```bash
(p35bd) troy@ascribe3-XPS-8700:~/repos/bigchaindb-driver$ python ~/Desktop/test2.py 
{'transaction': {'operation': 'CREATE', 'metadata': {'data': {'planet': 'earth'}, 'id': '697fea59-dfad-484e-9e59-4e4b43e9d4b7'}, 'asset': {'updatable': False, 'refillable': False, 'divisible': False, 'data': {'bicycle': {'serial_number': 'abcd1234', 'manufacturer': 'bkfab'}}, 'id': '28d76212-02e2-423d-af2d-0c5a6e3065ad'}, 'fulfillments': [{'input': None, 'fulfillment': 'cf:4:xoZK0HdlKwORY2snn74er3HUZKVNSTJyXMDoQRTGQhqgZbpS9wn8d2wuYom1gEhDfY88d9dUNkx8iO8ZSAXQ1el0WeMuLFqu3EO9Yt3-p2NXqAl6T88dPYRQOrMP1rgN', 'owners_before': ['EMxVb7Eovrn6RZMRSZuwBzw8YaXJ4WVeRVqgvUQuNbhT'], 'fid': 0}], 'conditions': [{'amount': 1, 'cid': 0, 'condition': {'details': {'type': 'fulfillment', 'bitmask': 32, 'signature': None, 'public_key': 'EMxVb7Eovrn6RZMRSZuwBzw8YaXJ4WVeRVqgvUQuNbhT', 'type_id': 4}, 'uri': 'cc:4:20:xoZK0HdlKwORY2snn74er3HUZKVNSTJyXMDoQRTGQho:96'}, 'owners_after': ['EMxVb7Eovrn6RZMRSZuwBzw8YaXJ4WVeRVqgvUQuNbhT']}]}, 'version': 1, 'id': '137f0f88307517bbd72a94b84ea7aaba0267970efc572346d6cd42f2bae0cc42'}
137f0f88307517bbd72a94b84ea7aaba0267970efc572346d6cd42f2bae0cc42
True
Traceback (most recent call last):
  File "/home/troy/Desktop/test2.py", line 25, in <module>
    while bdb.transactions.status(txid).get('status') != 'valid' and trials < 100:
  File "/home/troy/repos/bigchaindb-driver/bigchaindb_driver/driver.py", line 213, in status
    return self.transport.forward_request(method='GET', path=path)
  File "/home/troy/repos/bigchaindb-driver/bigchaindb_driver/transport.py", line 46, in forward_request
    response = connection.request(method=method, path=path, json=json)
  File "/home/troy/repos/bigchaindb-driver/bigchaindb_driver/connection.py", line 45, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.NotFoundError: (404, '{\n  "message": "Not found", \n  "status": 404\n}\n', {'message': 'Not found', 'status': 404})
```

I'm not exactly sure what's going on. Obviously a transaction with that `txid` wasn't found, and a `bigchaindb_driver.exceptions.NotFoundError` was raised, but why? What happened to the transaction?

If you wait long enough, an exception is _not_ raised. Instead, one gets back `'valid'`.

There are two issues here:

1. What happened to the transaction that cause it to be momentarily "not found"?
2. The while loop should keep going even if the transaction is not found, i.e. the exception shouldn't cause the while loop to terminate.

Note: This issue may be related to #174 but it's not the same.

**Comment by sohkai** [comment]
This is mostly likely because of how the status endpoint works; I suspect that because the transaction hasn't gone through to a decided state (it's still initially in an undecided state in the backlog table), we tell the client that it's not available.

We should revisit this with the HTTP API. There were some discussions about this a while back when we first implemented it, but I don't remember what the exact decision / reasoning was anymore.

**Comment by ttmc** [comment]
@sohkai  If the transaction is in the backlog or in an undecided block, then surely the status endpoint can report that, rather than "not found". Like you said, that's something to be handled by the server code (HTTP API), not the driver.

The second issue can still be taken care of, i.e. the exception shouldn't cause the while loop to terminate. Maybe something like this would work:
```python
trials = 0

while trials < 100:
    try:
        if bdb.transactions.status(txid).get('status') == 'valid':
            break
    except bigchaindb_driver.exceptions.NotFoundError:
        trials += 1

print(trials)
print(bdb.transactions.status(txid))
```

**Comment by ttmc** [comment]
Note: You can probably resolve #174 at the same time as this issue, since they're both about helping users understand and work with the fact that it takes some time for a transaction to get into a valid block.
