### ISSUE TITLE
invalid transaction schema: 'inputs' is a required property", 'status': 400

### ISSUE THREAD

**Issue by jiebanghan** [bigchaindb/bigchaindb-driver#211]
* bigchaindb-driver version:
* Python version:
* Operating System:

### Description
I run python below accroding to your webpage below:

from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair

bdb = BigchainDB('http://10.0.50.90:9984/api/v1')

bicycle = {
    'data': {
        'bicycle': {
            'serial_number': 'abcd1234',
            'manufacturer': 'bkfab',
        },
    },
}

metadata = {'planet': 'earth'}

alice, bob = generate_keypair(), generate_keypair()
prepared_creation_tx = bdb.transactions.prepare(
        operation='CREATE',
        owners_before=alice.verifying_key,
        asset=bicycle,
        metadata=metadata,
		#inputs={},
    )
print(prepared_creation_tx)
fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx, private_keys=alice.signing_key)
print(fulfilled_creation_tx)

but it shows:
Traceback (most recent call last):
  File "mybigchaindb.py", line 28, in <module>
    sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/driver.py", line 187, in send
    method='POST', path=self.path, json=transaction)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/transport.py", line 46, in forward_request
    response = connection.request(method=method, path=path, json=json)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/connection.py", line 45, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.TransportError: (400, '{\n  "message": "Invalid transaction schema: \'inputs\' is a required property", \n  "status": 400\n}\n', {'message': "Invalid transaction schema: 'inputs' is a required property", 'status': 400})

so how should I solve the problem?
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by TimDaub** [comment]
@jiebanghan and I resolved this via gitter.

He was using bigchaindb 0.9.0.dev instead of bigchaindb 0.8.0.
