### ISSUE TITLE
BigchainDB driver to accept custom http header types

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb-driver#212]
Feature request/enhancement.

We need a mechanism to set custom headers in the http API calls sent to the bigchaindb cluster backend.

**Comment by ttmc** [comment]
Some more context:  To send an authenticated request to a BigchainDB cluster, with the authentication handled by 3scale, two headers must be included in the HTTP request: `app_id: id_value` and `app_key: key_value`. There needs to be some way to tell the driver about those: maybe an optional `headers` dict in the initial call to BigchainDB(), e.g.
```python
bdb = BigchainDB(
    'http://apis-for-everyone.net:1234/api/v1',
    headers={'app_id': 'id_value', 'app_key': 'key_value'}
)
```

Other BigchainDB clusters might require other special HTTP request headers.
