### ISSUE TITLE
[docs] Add copy clipboard button for code samples

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#237]
### Resources
I am not sure on how to do this, so here is the beginning of a list of resources on that topic.

* http://stackoverflow.com/questions/39187220/how-to-add-a-copy-button-in-the-code-blocks-for-rst-read-the-docs

**Comment by kremalicious** [comment]
you need to create a custom Sphinx theme/template first. Then add the copy to clipboard button there (some HTML markup & js). Then publish the theme/template to pip. Then set and use that new theme for docs building.
