### ISSUE TITLE
Expose ability to generate public/private keypair in driver

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb-driver#26]
The driver should expose a way for the user to get a new public/private keypair for use with BigchainDB as they shouldn't have to care about any other BigchainDB package (e.g. bigchaindb-commons).

**Comment by ttmc** [comment]
I thought bigchaindb-common was to be a package that's needed by users of bigchaindb (server) and bigchaindb-driver, so whoever uses bigchaindb-driver will also get bigchaindb-common as a matter of course. Confused.

**Comment by sohkai** [comment]
@ttmc Yes, they would, the driver should just re-expose the utility from `bigchaindb-common`.

I'd prefer if users only had to deal with the driver rather than a bunch of other BigchainDB-related libs when they want to interact with a BigchainDB instance. This also makes it easier to define and provide similar drivers in other languages, e.g. javascript.
