### ISSUE TITLE
Feature - Retrieve a transaction ownership chain using the asset ID

### ISSUE THREAD

**Issue by cboothe** [bigchaindb/bigchaindb-driver#277]
* bigchaindb-driver version: 0.2.1
* Python version: 3.5.1 
* Operating System: OS X

### Description

Currently the only way to retrieve a transaction is by ID. However there is no way to retrieve a transaction ownership chain using the driver.

BigchainDB already has a get_transactions_filtered() method but doesn't allow both CREATE and TRANSFER operations to be searched at the same time. The operation would be sent as 'ALL' or a list of transactions to include. Given a created asset ID as the transaction ID return the CREATE transaction as well as any TRANSFER transactions.

**Comment by sbellem** [comment]
Hi @cboothe, did you try [.get()`](https://docs.bigchaindb.com/projects/py-driver/en/latest/libref.html#bigchaindb_driver.driver.TransactionsEndpoint.get)?

**Comment by cboothe** [comment]
Hi @sbellem, thanks for your help! That is exactly what I was looking for.
