### ISSUE TITLE
Installation Error - $ pip install --process-dependency-links git+https://github.com/bigchaindb/bigchaindb-driver.git

### ISSUE THREAD

**Issue by irfaans** [bigchaindb/bigchaindb-driver#282]
* bigchaindb-driver version:
* Python version: 3,6,2
* Operating System: Windows 10

### Description

From the documentation:

Installing latest master with pip
In order to work with the latest BigchainDB (server) master branch:

$ pip install --process-dependency-links git+https://github.com/bigchaindb/bigchaindb-driver.git
```
After some some installation I get the following error:

Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Armina\\AppData\\Local\\Temp\\pip-build-zlqobm40\\python-rapidjson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Armina\AppData\Local\Temp\pip-c5ylmpqu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Armina\AppData\Local\Temp\pip-build-zlqobm40\python-rapidjson\```

**Comment by irfaans** [comment]
Full output:

pip install --process-dependency-links git+https://github.com/bigchaindb/bigchaindb-driver.git
Collecting git+https://github.com/bigchaindb/bigchaindb-driver.git
  Cloning https://github.com/bigchaindb/bigchaindb-driver.git to c:\users\armina\appdata\local\temp\pip-ta5mw79x-build
  DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Collecting requests>=2.11.0 (from bigchaindb-driver==0.2.1)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 449kB/s
Collecting bigchaindb~=0.9.1 (from bigchaindb-driver==0.2.1)
  Downloading BigchainDB-0.9.5.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 940kB/s
Collecting rethinkdb~=2.3 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading rethinkdb-2.3.0.post6.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 473kB/s
Collecting pymongo~=3.4 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading pymongo-3.4.0.tar.gz (583kB)
    100% |████████████████████████████████| 583kB 548kB/s
Collecting pysha3~=1.0.2 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading pysha3-1.0.2-cp36-cp36m-win32.whl
Requirement already satisfied: cryptoconditions>=0.5.0 in c:\python36-32\lib\site-packages (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
Collecting python-rapidjson==0.0.11 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading python-rapidjson-0.0.11.tar.gz (154kB)
    100% |████████████████████████████████| 163kB 728kB/s
Collecting logstats>=0.2.1 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading logstats-0.2.1.tar.gz
Collecting flask>=0.10.1 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading Flask-0.12.1-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 809kB/s
Collecting flask-restful~=0.3.0 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading Flask_RESTful-0.3.5-py2.py3-none-any.whl
Collecting gunicorn~=19.0 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading gunicorn-19.7.1-py2.py3-none-any.whl (111kB)
    100% |████████████████████████████████| 112kB 826kB/s
Collecting multipipes~=0.1.0 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading multipipes-0.1.0.tar.gz
Collecting jsonschema~=2.5.1 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Collecting pyyaml~=3.12 (from bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 730kB/s
Requirement already satisfied: base58~=0.2.2 in c:\python36-32\lib\site-packages (from cryptoconditions>=0.5.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
Requirement already satisfied: PyNaCl~=1.0.1 in c:\python36-32\lib\site-packages (from cryptoconditions>=0.5.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
Collecting Werkzeug>=0.7 (from flask>=0.10.1->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading Werkzeug-0.12.1-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 749kB/s
Collecting Jinja2>=2.4 (from flask>=0.10.1->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 838kB/s
Collecting itsdangerous>=0.21 (from flask>=0.10.1->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 793kB/s
Collecting click>=2.0 (from flask>=0.10.1->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 882kB/s
Requirement already satisfied: six>=1.3.0 in c:\python36-32\lib\site-packages (from flask-restful~=0.3.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
Collecting aniso8601>=0.82 (from flask-restful~=0.3.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading aniso8601-1.2.0.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 900kB/s
Collecting pytz (from flask-restful~=0.3.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 707kB/s
Requirement already satisfied: cffi>=1.1.0 in c:\python36-32\lib\site-packages (from PyNaCl~=1.0.1->cryptoconditions>=0.5.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->flask>=0.10.1->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading MarkupSafe-1.0.tar.gz
Collecting python-dateutil (from aniso8601>=0.82->flask-restful~=0.3.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 779kB/s
Requirement already satisfied: pycparser in c:\python36-32\lib\site-packages (from cffi>=1.1.0->PyNaCl~=1.0.1->cryptoconditions>=0.5.0->bigchaindb~=0.9.1->bigchaindb-driver==0.2.1)
Installing collected packages: requests, rethinkdb, pymongo, pysha3, python-rapidjson, logstats, Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, flask, python-dateutil, aniso8601, pytz, flask-restful, gunicorn, multipipes, jsonschema, pyyaml, bigchaindb, bigchaindb-driver
  Running setup.py install for rethinkdb ... done
  Running setup.py install for pymongo ... done
  Running setup.py install for python-rapidjson ... error
    Complete output from command c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Armina\\AppData\\Local\\Temp\\pip-build-zlqobm40\\python-rapidjson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Armina\AppData\Local\Temp\pip-c5ylmpqu-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'rapidjson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Armina\\AppData\\Local\\Temp\\pip-build-zlqobm40\\python-rapidjson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Armina\AppData\Local\Temp\pip-c5ylmpqu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Armina\AppData\Local\Temp\pip-build-zlqobm40\python-rapidjson\

**Comment by sbellem** [comment]
Could you try installing Microsoft Visual C++ 14.0?
See last lines of full output:

> building 'rapidjson' extension
> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by codegeschrei** [comment]
Since there was no response for a really long time I assume the problem was solved :)
