### ISSUE TITLE
Fix broken shields in the first page of the docs

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#293]
The shields at the top of the first page of the docs are not loading properly, see:

https://docs.bigchaindb.com/projects/py-driver/en/latest/readme.html

![screenshot from 2017-06-16 14-29-02](https://user-images.githubusercontent.com/1210951/27226619-355a4298-52a0-11e7-9648-5ebcc626c41c.png)

**Comment by kremalicious** [comment]
shields.io craps out sometimes, had this too with some other repo's readmes. This usually solves itself, I can see all the badges in all the browsers right now

**Comment by TimDaub** [comment]
> shields.io craps out sometimes, had this too with some other repo's readmes. This usually solves itself, I can see all the badges in all the browsers right now

me2. Might be your browser, extensions or your internet connection at that time.

Closing.
