### ISSUE TITLE
Revisit transfer()'s inputs

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb-driver#30]
Currently, [transfer()](https://github.com/bigchaindb/bigchaindb-driver/blob/master/bigchaindb_driver/driver.py#L78) requires a user to specify a Transaction object from `bigchaindb-common` and a list of Condition objects from `bigchaindb-common`. Ideally, the user shouldn't have to worry about creating these objects and instead use their `id`s instead.

**Comment by sohkai** [comment]
Alternatively, @TimDaub and I had a discussion where it might make more sense if `bigchaindb_driver` exposed `bigchaindb_common`'s Transaction model to the end user. That way, `driver.transactions.retrieve` can also return a Transaction model (that should be much, much easier to work with than plain JSON).

**Comment by sohkai** [comment]
It may also be useful to expose a [`TransactionBuilder`](https://github.com/bigchaindb/bigchaindb-common/issues/12) from the driver if this gets implemented.

**Comment by sbellem** [comment]
For now, I propose we focus on what could be called a low-level driver, in which dictionaries are used for the data structure for response and request payloads. This will keep things simpler, and uniform for all endpoints.

**Comment by sohkai** [comment]
I'm not a big fan if that means we'll eventually write another package that's a high-level driver. I'd be ok with this if we exposed a convenient interface on the main `BigchainDB` object while the low-level stuff lives in `BigchainDB.raw` or similar.

Making cryptocondition dicts by hand is just way too hard for someone new or just wants basic functionality.

**Comment by sbellem** [comment]
All this involves is that the end-user of the driver passes and receives dictionaries, instead of Transaction model instances. The Transaction model is still used under the hood to perform the required operations, such as creating a `TRANSFER` transaction, using the inputs, and signing the transaction.

**Comment by TimDaub** [comment]
> All this involves is that the end-user of the driver passes and receives dictionaries, instead of a Transaction model instances.

Not sure how suitable this is. Creating a transfer is not as easy as giving a `transfer` method a couple of input transactions.

See here:
- https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L407
- https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L360
- https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L147

**Comment by sbellem** [comment]
@TimDaub both [`.to_inputs()`](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L407) and [`.transfer()`](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L360) are currently used "under the hood" and will still be used. 

I will make a PR and we can discuss if needed around the PR itself, it will be more productive this way and will help prevent misunderstandings.

**Comment by sbellem** [comment]
@sohkai and @TimDaub can we close this issue since `.transfer` is being deprecated, and given the changes introduced by #109?

As for the question of the design choices, and whether the driver should deal with dictionaries or expose models, I propose to discuss these matters in a separate issue. 

If you can be a bit patient, and wait for the design document that should come out of #156, the discussion may be more productive and grounded then.

**Comment by TimDaub** [comment]
:+1:

**Comment by sbellem** [comment]
### status
* @TimDaub has provided his fulfillment
* waiting for @sohkai's fulfillment

:smirk:

**Comment by sohkai** [comment]
👍
