### ISSUE TITLE
Replace changelog content with hyperlink in long_description in setup.py

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#320]
The exact effective date of a release cannot be known in advanced with certainty, and since the `CHANGELOG.rst` file goes through the review process, and includes the release date, it would be best if the `CHANGELOG` was merged after the release not before. This would allow us to accurately set the release date in the `CHANGELOG`.

As of now the content of the `CHANGELOG` is displayed on PyPI, and cannot be changed, without making a new release. This could be a never ending problem, hence the proposed approach.

**Comment by ttmc** [comment]
I'm not sure I understand. What would the link URL be?

**Comment by sbellem** [comment]
> I'm not sure I understand. What would the link URL be?

oh, simply the to the file on github: https://github.com/bigchaindb/bigchaindb-driver/blob/master/CHANGELOG.rst

**Comment by ttmc** [comment]
Sounds good.
