### ISSUE TITLE
BigchainDB support for Django

### ISSUE THREAD

**Issue by crossoveranx** [bigchaindb/bigchaindb-driver#342]
* bigchaindb-driver version:
* Python version: 3.6
* Operating System: Ubuntu 16.04

### Description

Is it possible to link bigchain-DB to various python backends, such as django or flask? Since it is built on top of mongoDB I thought it may be possible, but I had some trouble figuring this out. Please let me know if there is a solution in the docs about this

**Comment by sbellem** [comment]
We do not have a specific streamlined way to do this right now, but you can definitely use the Python driverr from your django project to connect and interact with a BigchainDB cluster. The docs for the Python driver are are at https://bigchaindb.readthedocs.io/projects/py-driver/, whereas the docs for the server are at https://bigchaindb.readthedocs.io/en/latest/index.html

We can provide you with much more guidance on that matter if you need. Rather than flooding you with information I'll wait for your questions and will do my best to help you.

**Comment by onestan2** [comment]
I'd like to see if a couple starting points make sense: (1) Within a project, create an django app with models having methods that can make CRAB calls to BigchainDB cluster via the driver - in short a wrapper. I'm making the assumption that the db specified in django settings (e.g. postgres) is not used (even though it could be) to store asset or transaction-based info; that's all stored in the BigChainDB cluster.  (2) Create a django model that is used to represent the asset (or a python dictionary [json or xml object from an api call] can suffice at a minimum). However, the asset(s) and transactions related to the same all reside in BigchainDB; Django's primary function is simply a well-defined framework (a) to define/create assets through it's interface, (b) to perform operations on attributes of assets within the app outside of official BigChainDB transactions (e.g., advanced analytics, ML), (b) facilitate usual interactions within views and UI displays within Dango templates, and (c) allow permissioned or permissionless api calls from 3rd parties to leverage the Django + BigchainDB capabilities using django rest framework.  Let me know if my thinking is off or if I have some blind spots on a general strategy,  I am relatively new to this and have been thinking about BigChainDB for the AI work that I do but I wanna make sure this is a reasonable approach.

**Comment by ttmc** [comment]
As of BigchainDB 2.0, every BigchainDB node has its own independent, local MongoDB database. The node operator can choose how to expose the information to external applications. It's totally possible that they could use Django to create a web app for querying their node's MongoDB database, or they could let some external partner do that (by giving them, and only them, the necessary MongoDB auth credentials).

There are many tools to use MongoDB with Django. Google can help you find them.

**Comment by onestan2** [comment]
I'm familiar with the Django MongoDB engine and am pursuing this path.  Thanks, Trent!

**Comment by ttmc** [comment]
You're welcome!

Troy
