### ISSUE TITLE
Not able to connect with local server 

### ISSUE THREAD

**Issue by gouri96** [bigchaindb/bigchaindb-driver#351]
* bigchaindb-driver version:
* Python version:
* Operating System:

### Description

I installed mongodb and bigchaindb driver.
but i am unable to connect with mongodb
code :

```python
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair


bdb = BigchainDB('http://127.0.0.1:9985')

alice = generate_keypair()


m_1={'data': {'msg': 'Hello BigchainDB 1!'},}


prepared_creation_tx = bdb.transactions.prepare(
    operation='CREATE',
    signers=alice.public_key,
    asset=m_1
)
fulfilled_creation_tx = bdb.transactions.fulfill(
    prepared_creation_tx, private_keys=alice.private_key)
bdb.transactions.send(fulfilled_creation_tx)


Error: 
Traceback (most recent call last):
  File "coe.py", line 20, in <module>
    bdb.transactions.send(fulfilled_creation_tx)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb_driver/driver.py", line 319, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.TransportError: (500, '', None)
```

### What I Did

```
first i run this command
mongod --replSet=bigchain-rs
then start the server
bigchaindb start


then run the python code.

```

**Comment by vrde** [comment]
Can you please tell me:
- bigchaindb version
- bigchaindb-driver version
- Python version
- Operating System

**Comment by gouri96** [comment]
bigchaindb version- bigchaindb 1.3.0
bigchaindb-driver - from github i have downloaded 
Python 3.4.3
Ubuntu 14.04 trusty

**Comment by codegeschrei** [comment]
Hey @gouri96 we just updated the driver and server to a new version. Can you try it again?

**Comment by codegeschrei** [comment]
hey @Vasista-22 
you need to add the tags when installing it with pip/pip3
```
pip install bigchaindb==v2.0.0a1
pip install bigchaindb-driver==v0.5.0a1
```
If you want to use docker, we updated the Makefile so you can just easily go with ```make start``` and everything should be up and running

**Comment by codegeschrei** [comment]
closing this for now
@gouri96 feel free to reopen when you have further questions :)

**Comment by saikumar-neelam** [comment]
same error Traceback (most recent call last):
  File "sample1.py", line 44, in <module>
    print(sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx))
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 411, in send_commit
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 82, in forward_request
    backoff_cap=backoff_cap,
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 76, in request
    raise TimeoutError
TimeoutError

**Comment by Vasista-22** [comment]
Hi Saikumar,
When I had this similar error, I've reinstalled bigchaindb1.0.1.
Few reasons for this could be:
1. If you are trying to install bigchaindb in a proxied environment it
could lead to such errors.
2. If you haven't tried sudo -E option after setting environment variables
for your proxy do that.

The best solution would be to purge your existing version and re-install
without having a proxied internet connection, by following the instructions
in the bigchaindb documentation.

Regards,
Vasista

**Comment by saikumar-neelam** [comment]
Thanks Vasista,

its working fine for single node. but how to work with multiple nodes .i.e., persistent peers.
what are the changes to be done in genesis.json and config.toml files to work with multiple nodes


Regards,
Sai Kumar
