### ISSUE TITLE
Did there somebody could tell me how the bigchaindb driver CRAB asset? just like js-driver-orm does.

### ISSUE THREAD

**Issue by sportscar** [bigchaindb/bigchaindb-driver#354]
* bigchaindb-driver version:0.4.1
* Python version:3.5.2
* Operating System:ubuntu 16.04

### Description

I just read the blog :[ CRAB — Create. Retrieve. Append. Burn.
](https://blog.bigchaindb.com/crab-create-retrieve-append-burn-b9f6d111f460)
My business logic mostly like this. but I'm use python, not js. So,  I want to know how can I do it with python:

    Create an asset;
    Retrieve it;
    Append it;
    Show the history of asset;

Thanks!

**Comment by manolodewiner** [comment]
Hi @sportscar  we are currently not planning to build the CRAB implementation for the Python language. Note that the `searchMetadata` isn't implemented in the `js-driver-orm` so most of the people stopped using it.
You can easily do all of the CRAB actions using the Python driver, so please just have a look at the [docs](https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html).
And let us know if you have any other question in our [Gitter] (https://gitter.im/bigchaindb/bigchaindb)
