### ISSUE TITLE
Problem: transaction query parameter mode is not implemented

### ISSUE THREAD

**Issue by codegeschrei** [bigchaindb/bigchaindb-driver#359]
Solution: add and document mode parameter for transactions

https://github.com/bigchaindb/bigchaindb/pull/1951

**Comment by ttmc** [comment]
That's odd. I thought it _was_ implemented and documented. 

Docs: https://docs.bigchaindb.com/projects/server/en/tendermint/http-client-server-api.html#post--api-v1-transactions?mode=mode

Implementation: https://github.com/bigchaindb/bigchaindb/blob/tendermint/bigchaindb/web/views/transactions.py#L59

(in the `tendermint` branch, of course)
