### ISSUE TITLE
Problem: Dev environment is outdated and no integration with Tendermint

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb-driver#368]
* bigchaindb-driver version: `master`
* bigchaindb **server** version (`bigchaindb -v`): `master/tendermint`
* Python version: `n/a`
* Operating System: `n/a`

### Description
Currently, the development environment of BigchainDB Python driver is outdated and is not integrated with Tendermint i.e. BigchainDB v2.0 is integrated with Tendermint but the driver development enviroment still uses BigchainDB <=1.3.0.

Update the development environment:
- Update `docker-compose.yml`
- Remove `docker-compose.rdb.yml` because RethinkDB is not supported with BigchainDB v2.0
- Update Travis configuration to test with `localmongodb` and BigchainDB v2.0 instead of BigchainDB <=1.3.0 and `rethinkdb`.
- Consolidate all deployment methods in a single `docker-compose` file i.e. `docs.yml` should move into `docker-compose.yml` as well.

**Comment by codegeschrei** [comment]
related to #358
