### ISSUE TITLE
Problem: tests are sometimes failing because a transaction is not yet in a block

### ISSUE THREAD

**Issue by codegeschrei** [bigchaindb/bigchaindb-driver#386]
Solution: change the default mode for sending transactions to commit, to wait for a transaction to be committed to a block

**Comment by manolodewiner** [comment]
FYI: In the JS Driver for every tests we always use the commit mode when sending trasactions

**Comment by codegeschrei** [comment]
We will do it now too. For tests and in general. If people want to have a different mode they have to specify it.
