### ISSUE TITLE
Problem: The Quickstart documentation does not link to BDB setup

### ISSUE THREAD

**Issue by codegeschrei** [bigchaindb/bigchaindb-driver#394]
Solution: reference BigchainDB setup

In the Quickstart documentation we only show how to run the driver, which is basically fine, but it might help users if we add links how to set up and run BigchainDB too.

**Comment by ttmc** [comment]
Maybe link to the Quickstart page for BigchainDB Server?

https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html

**Comment by ttmc** [comment]
Resolved by PR #424
