### ISSUE TITLE
Problem: Some users unable to upgrade to the latest version

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#396]
The latest version of the Python driver, 0.5.0a1, is a "pre-release" (or at least that's what I heard; I couldn't find any indication of this fact on PyPI, i.e. at https://pypi.python.org/pypi/bigchaindb-driver ). That means that just doing:
```bash
$ pip install -U bigchaindb_driver
```

will not upgrade them to 0.5.0a1, because it's not a "release", it's a pre-release. They must do:
```bash
$ pip install bigchaindb_driver==0.5.0a1
```

### To Do

- Figure out how to get PyPI to indicate that it's a pre-release.
- Update the docs (including those on PyPI) on how to install / upgrade the driver, to account for the case when the latest version is a pre-release.

**Comment by codegeschrei** [comment]
> Remove all mention of how to update the Python driver from the README.md because PyPI automatically takes care of that now.

But removing it from the readme is not helpful for people who just visit the GitHub repo.

**Comment by ttmc** [comment]
> But removing it from the readme is not helpful for people who just visit the GitHub repo.

Maybe the `README.rst` file could point to the PyPI page listing all releases and pre-releases, each of which has its own page with the correct instructions on how to install it, instructions which _change over time_!

https://pypi.org/project/bigchaindb-driver/#history

**Comment by codegeschrei** [comment]
ok, I think this makes sense.
