### ISSUE TITLE
Missing common directory when using setup.py

### ISSUE THREAD

**Issue by agwego** [bigchaindb/bigchaindb-driver#415]
* bigchaindb-driver version: current master 0.5.0a2, 0.5.0a3
* bigchaindb **server** version (`bigchaindb -v`): 1.0.1
* Python version: 3.5.2
* Operating System: Ubuntu 16.04.3 LTS

### Description
Installing with python3 setup.py install, fails to include the common files, which causes the driver to fail when importing file in common.

### What I Did
Added the following line to the MANIFEST.in file to make it work.
`recursive-include bigchaindb_driver/common *`
`python3 setup.py install`

**Comment by ttmc** [comment]
@agwego We _just_ released a new version of the Python driver, 0.5.0a3

Maybe try installing and using that version instead. To install it:

`pip install bigchaindb-driver==0.5.0a3`

**Comment by vrde** [comment]
@agwego thanks for your issue. We recently added a new module to the driver and we didn't update `setup.py` property (side note: I assumed it was using `find_packages`). See #417 and #418. We will release `0.5.0a4` in a minute.

**Comment by vrde** [comment]
@agwego the new version has been uploaded, you can install it with `pip install bigchaindb-driver==0.5.0a4`.

**Comment by agwego** [comment]
```
root@u138:~# pip3 install bigchaindb-driver==0.5.0a4  
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip._internal'
```

**Comment by vrde** [comment]
@agwego this is something that do not depend on us. From what I read, it seems like `pip` has not been installed correctly. Online I found that [reinstalling `pip` should do the trick](https://askubuntu.com/questions/1025189/pip-is-not-working-importerror-no-module-named-pip-internal). Can you give it a try?

**Comment by agwego** [comment]
Yes that worked, thanks.

**Comment by vrde** [comment]
Thanks for the quick feedback! I'll close the issue now.
