### ISSUE TITLE
When 

### ISSUE THREAD

**Issue by agwego** [bigchaindb/bigchaindb-driver#416]
* bigchaindb-driver version: master 0.5.0a3
* bigchaindb **server** version (`bigchaindb -v`): 1.0.1
* Python version: 3.5.2
* Operating System: Ubuntu 16.04.3 LTS

### Description

I'm trying to create an asset against a V1 Bigchaindb and I'm getting the following error:
`error: message  (400, '{\n  "message": "Invalid transaction schema: \'2.0\' does not match \'^1\\\\\\\\.0$\'", \n  "status": 400\n}\n', {'status': 400, 'message': "Invalid transaction schema: '2.0' does not match '^1\\\\.0$'"})
`
### What I Did

bdb.transactions.send( transactionSigned )

**Comment by ttmc** [comment]
The BigchainDB Python drivers with versions 0.5.0a1, 0.5.0a2 and 0.5.0a3 will only build transactions conforming to the [BigchainDB Transactions Spec v2](https://github.com/bigchaindb/BEPs/tree/master/13), which is the only version of transactions that BigchainDB 2.0 will accept.

**Comment by ttmc** [comment]
Note: We broke backwards-compatibility and migrate-ability going from BigchainDB 1.3 to 2.0, but in the future, there will always be a migration path to subsequent versions.

**Comment by codegeschrei** [comment]
I'm going to close this for now.
@agwego feel free to ask more questions here, in a new issue or on gitter :)

**Comment by shubhamc15** [comment]
As per the Documentation the compabitlity veriosn of my BigchainDB version == 2.0.0a1 and bigchaindbdriver version == 0.5.0a4.
while creating transaction i am getting following error:
bigchaindb_driver.exceptions.BadRequest: (400, '{"message":"Invalid transaction schema: \'2.0\' does not match \'^1\\\\\\\\.0$\'","status":400}\n', {'status': 400, 'message': "Invalid transaction schema: '2.0' does not match '^1\\\\.0$'"})

**Comment by NasimShourav** [comment]
Hello! I also got the same error whenever I try to do 
**sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx).** 
Error:
**(400, '{"message":"Invalid transaction schema: \'2.0\' does not match \'^1\\\\\\\\.0$\'","status":400}\n', {'message': "Invalid transaction schema: '2.0' does not match '^1\\\\.0$'", 'status': 400}, 'http://127.0.0.1:9984//api/v1/transactions/')**

I am using ubuntu 16.04
bigchaindb stable version and driver from **https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-installation.html**
