### ISSUE TITLE
Problem installing python driver

### ISSUE THREAD

**Issue by rromanss23** [bigchaindb/bigchaindb-driver#420]
* bigchaindb-driver version: -
* bigchaindb **server** version (`bigchaindb -v`): 1.01
* Python version: 3.6.4
* Operating System: Linux - Ubuntu 17.10

### Description

Hi all! I’m currently developing an IoT project as my End of Degree in Industrial Engineering Project, and the goal is to implement it with Blockchain technology to have it completely decentralized. I’m quite noob both in programming and with blockchain technologies and I am a bit lost so any help will be greatly appreciated!

Up to now, the project (programmed in python) it can be seen in the following repo if someone wants to take a look at it

https://github.com/rromanss23/Uploading-sensor-data-to-IOTA-tangle

And works as follows:

    There’s environment data collected from a sensor attached to a Raspberry Pi.
    Data is published via MQTT.
    A linux machine is subscribed to the MQTT channel and:
        Stores it in a MySQLdb database
        Computes a temporal statistic summary and publish it to the IOTA tangle

As the next step of the project is to don’t need the MySQLdb, I’m trying to set up a BigchainDB database to do its functions. As I’ve read from the docs I believe that the adequate set up would be to create and asset as the Raspberry Pi and upload its metadata with each data measurement.

1) Please someone correct me if this is not the right approach for what I am trying to achieve.

Currently I am facing several problems, descripted in ### What I Did

Thank you very much in advance for the help and keep up with the great job guys! I believe that BichainDB is a great project with lots of possible use cases! 

### What I Did

```
- When trying to install the python driver: pip3 install -U bigchaindb-driver

pyopenssl 17.5.0 has requirement cryptography>=2.1.4, but you'll have cryptography 1.9 which is incompatible.
jupyterlab-launcher 0.10.2 has requirement jsonschema>=2.6.0, but you'll have jsonschema 2.5.1 which is incompatible.

- When trying to update OpenSSL:

AttributeError: module 'lib' has no attribute 'X509_up_ref'

- I’ve been trying also to work with the testnet to see if I could pass through this issue but the following pops up:

From cffi callback <function _verify_callback at 0x7f40c46ba158>:
Traceback (most recent call last):
File "/home/vroman/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 313, in wrapper
_lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
```

**Comment by ttmc** [comment]
The latest Python Driver is version 0.5.0a4. To install that, see the instructions at the top of that version's page on PyPI: https://pypi.org/project/bigchaindb-driver/0.5.0a4/

`pip install bigchaindb-driver==0.5.0a4`

Maybe that will resolve everything, maybe not. If not, then try Googling the error message.

**Comment by rromanss23** [comment]
Tried it, and the same error appears. 
Already googled the error message and unable to find an adequate solution...

**Comment by ttmc** [comment]
Okay, first of all, create a Python virtualenv or equivalent (e.g. a fresh VM), and try again in there. If it still doesn't work, then you probably need to install some more dependencies. This might suffice:

```text
$ sudo apt-get update
$ sudo apt-get install libffi-dev libssl-dev
$ sudo apt-get install python3-pip
$ sudo pip3 install --upgrade pip setuptools
```

And use the `pip3` command rather than the `pip` command going forward.

**Comment by rromanss23** [comment]
Solved it! There were some incompatibilities with some libraries missing in my computer. Anaconda was interfering with the installation. I uninstalled Anaconda and was able to install the driver without issues.
Thanks for the help ttmc!
