### ISSUE TITLE
Basic Usage Examples incorrect documentation

### ISSUE THREAD

**Issue by aruseni** [bigchaindb/bigchaindb-driver#436]
> Also note how, because we were consuming a ``TRANSFER`` transaction, we were
> able to directly use the ``TRANSFER`` transaction's ``asset`` as the new
> transaction's ``asset`` because it already contained the asset's id.

Actually if using the example, a ``CREATE`` transaction is consumed, and its ID is used.

**Comment by codegeschrei** [comment]
Hey @aruseni 
Nice catch! Would you like to make a pull request and fix it? :)

**Comment by aruseni** [comment]
Yeah, sure. I just wanted to mention it here first so I am certain that I did not misunderstood it. :)
