### ISSUE TITLE
Demo script: 'bike_token_id' is not defined

### ISSUE THREAD

**Issue by giddyhup** [bigchaindb/bigchaindb-driver#449]
* bigchaindb-driver version: v0.5.0
* bigchaindb **server** version (`bigchaindb -v`): 2.0.0b1
* Python version: 3.5.2
* Operating System: Ubuntu

### Description

Demo from the driver's landing page fails with an error about 'bike_token_id' being undefined.

### What I Did

ran the demo script
```
nameError: name 'bike_token_id' is not defined
```

**Comment by codegeschrei** [comment]
Hey @giddyhup 

That's a mistake. I'll fix it later.
For now you have to use `bike_token` instead. 
Or if you want you can make a PR too and fix it :)

**Comment by giddyhup** [comment]
@codegeschrei thanks for the quick reaction. I thought so
Yet, it looks like there are additional errors after that:
```
/bigchaindb_driver/common/transaction.py", line 717, in transfer
    raise TypeError('`asset_id` must be a string')
TypeError: `asset_id` must be a string

```

**Comment by giddyhup** [comment]
I checked, it's a dict.

**Comment by codegeschrei** [comment]
Hey @giddyhup 
I'm sorry, I gave you the wrong information
you need to replace 
this line
```
transfer_asset = {'id': bike_token_id}
```
with 
```
transfer_asset = {'id': fulfilled_token_tx['id']}
```
