### ISSUE TITLE
Some users are unable to install the latest Python driver

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#457]
Some users have reported that they are unable to install the latest Python driver, both on Ubuntu and on Windows. See the following message (and subsequent messages) on Gitter:

https://gitter.im/bigchaindb/bigchaindb?at=5b41623481816669a4394dbc

**Comment by prsn05** [comment]
hello all, I am trying to install "bigchaindb_driver" but pynacl is not installing. Pynacl version 1.1.2 is giving errors while installing and the latest one Pynacl 1.2.1 in incompatible. What should I do? Please help.
![untitled](https://user-images.githubusercontent.com/11696196/42422368-71303cda-8302-11e8-9a6b-a12e8a350b28.png)

**Comment by ttmc** [comment]
@prsn05 

1) It seems you're using Python 3.7, which just got released. I'm not sure if we've tested BigchainDB with Python 3.7 yet. Maybe try using Python 3.6 instead.

2) It seems you're using Windows. We don't go out of our way to support Windows. I think the JS driver might work on Windows. You could also try installing the Python driver in a Linux VM.

**Comment by prsn05** [comment]
@ttmc 
Thank you very much, Python 3.6 was the solution.
