### ISSUE TITLE
Unable to install driver on 64 bit windows and python 3.7

### ISSUE THREAD

**Issue by ankitgaur** [bigchaindb/bigchaindb-driver#498]
* bigchaindb-driver version:
* bigchaindb **server** version (`bigchaindb -v`):
* Python version: 3.7
* Operating System: Windows 10

### Description

Describe what you were trying to get done.
Trying to install bigchaindb driver and get following error :-

  error: [WinError 193] %1 is not a valid Win32 application

  ----------------------------------------
  Failed building wheel for PyNaCl
  Running setup.py clean for PyNaCl
Failed to build PyNaCl
Installing collected packages: python-rapidjson-schema, python-rapidjson, pysha3, asn1crypto, cryptography, pyasn1, PyNaCl, cryptoconditions, bigchaindb-driver
  Running setup.py install for PyNaCl ... error
    Complete output from command C:\Users\a82250\AppData\Local\Continuum\anaconda3\envs\blockchaindb\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\a82250\\AppData\\Local\\Temp\\pip-install-yy6qvve2\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\a82250\AppData\Local\Temp\pip-record-eog4e3zg\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\nacl
    copying src\nacl\encoding.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\exceptions.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\hash.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\hashlib.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\public.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\pwhash.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\secret.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\signing.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\utils.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\__init__.py -> build\lib.win-amd64-3.7\nacl
    creating build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_generichash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_pwhash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_shorthash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\utils.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win-amd64-3.7\nacl\bindings
    running build_clib
    error: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "C:\Users\a82250\AppData\Local\Continuum\anaconda3\envs\blockchaindb\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\a82250\\AppData\\Local\\Temp\\pip-install-yy6qvve2\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\a82250\AppData\Local\Temp\pip-record-eog4e3zg\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\a82250\AppData\Local\Temp\pip-install-yy6qvve2\PyNaCl\

### What I Did

```
pip install -U bigchaindb-driver
```

**Comment by ttmc** [comment]
The problem is that PyNaCl (cryptographic software) requires some operating system dependencies and I'm not sure how you get those dependencies installed on Windows, or if that's even possible.

You will save yourself a lot of trouble by using Linux or macOS instead of Windows. Windows has a "Windows Subsystem for Linux" (WSL) available on the Windows Store (under "Ubuntu"). Maybe try using that. If that doesn't work, then maybe try a virtual machine with Ubuntu inside it.

**Comment by ankitgaur** [comment]
made it to work using an ubuntu emulator on windows.

**Comment by ttmc** [comment]
Great!
