### ISSUE TITLE
Driver should take host of nodes, not specific API path

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-driver#69]
Currently the driver class takes any URI as a valid parameter for a URI pointing to a BDB node:
See: https://github.com/bigchaindb/bigchaindb-driver/blob/master/bigchaindb_driver/driver.py#L34

When doing requests, the connection's `path` just specifies the path on a single level (e.g. `/transactions`), so that when initializing the driver with:

`Driver('http://ipdb.foundation', 'http://localhost:9984')`

requests fail, as for both specified URIS, their path to the API + VERSION is missing.
To fix the earlier given example:

`Driver('http://ipdb.foundation/api/v1', 'http://localhost:9984/api/v1')`.

This ticket suggests to add the paths in the initialization method of the driver to the node-URI given by the user.

**Comment by sbellem** [comment]
@TimDaub this was a known (not documented) limitation for the first cut. Will take care of improving it now.

**Comment by TimDaub** [comment]
Cool!
