### ISSUE TITLE
Review temp_driver()

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb-driver#70]
Should `temp_driver` still exist? And if we do still want to keep this functionality, should we roll it up into an initialization flag for the driver (e.g. `BigchainDB(autogen_keypair=True)`)?

**Comment by sbellem** [comment]
Good question. Perhaps @vrde may share his thoughts on this as well.

I like the proposed alternative

```python
BigchainDB(autogen_keypair=True)
```

**Comment by sbellem** [comment]
As the [usage example](https://github.com/bigchaindb/bigchaindb-driver/blob/master/docs/usage.rst) shows, the `temp_client` is not essential, and we could remove it.

**Comment by sbellem** [comment]
Will remove it.
