### ISSUE TITLE
Define BichainDB API v1.1 Client API

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb-driver#8]
Based on the API spec provided by https://github.com/bigchaindb/bigchaindb/issues/362, define the API that the Python client should provide. This should be generic enough such that a [Javascript](https://github.com/bigchaindb/bigchaindb/issues/256) / go / etc. client can be modelled after it.

May be useful to gain inspiration from:

* [elasticsearch-py](https://github.com/elastic/elasticsearch-py) (low-level client): [Honza Král - Lessons learned from building Elasticsearch client](https://youtu.be/XoZDdwz43uQ)
* [elastisearch-dsl-py](https://github.com/elastic/elasticsearch-dsl-py) (ORM-like client): [Honza Král - Designing a Pythonic Interface](https://youtu.be/FPQrUuddT0s)

**Comment by sohkai** [comment]
Some thoughts from #21:
* The current actions should probably be suffixed with `transactions`
* The current actions could return an object that exposes a number of useful things to clients (e.g. `transaction.url`, `transaction.id`, `transaction.json`, `transaction.status` and etc.)

**Comment by sbellem** [comment]
@sohkai  see #33

**Comment by sohkai** [comment]
With #59 this should be done, barring any issues found during integration with pycoalaip and pycoalaip-bigchaindb.
