### ISSUE TITLE
Testing code examples and auto-generating their output

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#82]
Once we have some example code showing how to use the Python driver API, we should consider:
1. testing the code snippets (to see if they throw exceptions)
2. auto-generating the output to be consistent with the actual output

Maybe we can use the Sphinx extension named doctest? See http://www.sphinx-doc.org/en/stable/ext/doctest.html

Note that RethinkDB and BigchainDB would have to be configured and running. That might not be possible on ReadTheDocs.

Another option is to use an IPython Notebook (i.e. run it and then convert the finished notebook to .rst).

This issue was inspired by https://github.com/bigchaindb/bigchaindb/issues/607 and https://github.com/bigchaindb/bigchaindb/issues/637

**Comment by sohkai** [comment]
We've chosen to use the IPython plugin for Sphinx.
